#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-siesta
Version  : 1.5.2
Release  : 2
URL      : https://repo1.maven.org/maven2/org/sonatype/sisu/siesta/siesta-client/1.5.2/siesta-client-1.5.2.jar
Source0  : https://repo1.maven.org/maven2/org/sonatype/sisu/siesta/siesta-client/1.5.2/siesta-client-1.5.2.jar
Source1  : https://repo1.maven.org/maven2/org/sonatype/sisu/siesta/siesta-client/1.5.2/siesta-client-1.5.2.pom
Source2  : https://repo1.maven.org/maven2/org/sonatype/sisu/siesta/siesta-common/1.5.2/siesta-common-1.5.2.jar
Source3  : https://repo1.maven.org/maven2/org/sonatype/sisu/siesta/siesta-common/1.5.2/siesta-common-1.5.2.pom
Source4  : https://repo1.maven.org/maven2/org/sonatype/sisu/siesta/siesta/1.5.2/siesta-1.5.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-siesta-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-siesta package.
Group: Data

%description data
data components for the mvn-siesta package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-client/1.5.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-client/1.5.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-client/1.5.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-client/1.5.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-common/1.5.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-common/1.5.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-common/1.5.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-common/1.5.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta/1.5.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta/1.5.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-client/1.5.2/siesta-client-1.5.2.jar
/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-client/1.5.2/siesta-client-1.5.2.pom
/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-common/1.5.2/siesta-common-1.5.2.jar
/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta-common/1.5.2/siesta-common-1.5.2.pom
/usr/share/java/.m2/repository/org/sonatype/sisu/siesta/siesta/1.5.2/siesta-1.5.2.pom
